# monitoring/prometheus.yml
global:
  scrape_interval: 15s      # scrape every 15 seconds
  evaluation_interval: 15s


scrape_configs:
  - job_name: 'kidney-stone-api'
    static_configs:
      - targets: ['host.docker.internal:8000']
    metrics_path: '/metrics'
